### ISSUE TITLE
مشکل با پرداخت MYKET

### ISSUE THREAD

**Issue by Mehrdad1991h** [nivadcloud/InAppBillingAndroidSample#4]
سلام و وقت بخیر
ببخشید من الان داخل برنامه برای بازار و مایکت از این استفاده کردم
ولی جالب اینجاست ک بازار بدون مشکل کار میکنه
ولی مایکت بیلینگ سرویس نال میمونه و هیچ اتفاقی رخ نمیدهد
مشکل از چیست ؟
(هر دو حالت دقیقا مثل هم پیش میرن و فقط کد های دسترسی و نام و.. تغییر میکنن

**Comment by MJafarMashhadi** [comment]
Myket has recently made breaking, backward incompatible changes to its API without any prior notice and without versioning. They completely broke the mechanism we used to verify purchases.

It is fixed now but requires an additional step from you, the developer. Log in to your Nivad developer console, open up secure billing settings and follow the instructions there to re-activate the Nivad-Myket connection.
